# 16. Simultaneous Equations Models 

## 16.1 Setup and Notation

## 16.2 Estimation by 2SLS

### 16.5: Labour Supply of Married, Working Women

## 16.3 Outlook: Estimation by 3SLS

In [2]:
import wooldridge as woo
import linearmodels.system as iv3
import numpy as np

mroz = woo.dataWoo("mroz").dropna(subset= ["lwage"])
mroz.head()

,inlf,hours,kidslt6,kidsge6,age,educ,wage,repwage,hushrs,husage,...,faminc,mtr,motheduc,fatheduc,unem,city,exper,nwifeinc,lwage,expersq
0,1,1610,1,0,32,12,3.3540,2.65,2708,34,...,16310.0,0.7215,12,7,5.0,0,14,10.910060,1.210154,196
1,1,1656,0,2,30,12,1.3889,2.65,2310,30,...,21800.0,0.6615,7,7,11.0,1,5,19.499981,0.328512,25
2,1,1980,1,3,35,12,4.5455,4.04,3072,40,...,21040.0,0.6915,12,7,5.0,0,15,12.039910,1.514138,225
3,1,456,0,3,34,12,1.0965,3.25,1920,53,...,7300.0,0.7815,7,7,5.0,0,6,6.799996,0.092123,36
4,1,1568,1,2,31,14,4.5918,3.60,2000,32,...,27300.0,0.6215,12,14,9.5,1,7,20.100058,1.524272,49

In [4]:
formula = {"eq1": "hours ~ 1 + educ + age + kidslt6 + nwifeinc + [np.log(wage) ~ exper + I(exper**2)]",
           "eq2": "np.log(wage) ~ 1 + educ + exper + I(exper**2) + [hours ~ age + kidslt6 + nwifeinc]"}
reg_3sls = iv3.IV3SLS.from_formula(formula, data = mroz)
results_3sls = reg_3sls.fit(cov_type = "unadjusted",
                           debiased = True)
results_3sls

                           System GLS Estimation Summary
===================================================================================
Estimator:                        GLS   Overall R-squared:                  -2.3957
No. Equations.:                     2   McElroy's R-squared:                 0.7846
No. Observations:                 428   Judge's (OLS) R-squared:            -2.3957
Date:                Tue, Dec 27 2022   Berndt's R-squared:                  0.5181
Time:                        10:58:09   Dhrymes's R-squared:                -2.3957
                                        Cov. Estimator:                  unadjusted
                                        Num. Constraints:                      None
                    Equation: eq1, Dependent Variable: hours
================================================================================
              Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
--------------------------------------------------------------------------------
Intercept        2305.9     511.54     4.5077     0.0000      1300.4      3311.3
age             -9.5150     7.9609    -1.1952     0.2327     -25.163      6.1331
educ            -212.82     53.727    -3.9611     0.0001     -318.43     -107.21
kidslt6         -192.36     150.92    -1.2746     0.2032     -489.00      104.28
nwifeinc        -0.1770     3.5836    -0.0494     0.9606     -7.2210      6.8670
np.log(wage)     1781.9     439.88     4.0509     0.0001      917.30      2646.6

==================
   Instruments
------------------
I(exper**2), exper

                Equation: eq2, Dependent Variable: np.log(wage)
===============================================================================
             Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
-------------------------------------------------------------------------------
Intercept      -0.6939     0.3360    -2.0653     0.0395     -1.3543     -0.0335
I(exper**2)    -0.0003     0.0003    -1.1303     0.2590     -0.0008      0.0002
educ            0.1127     0.0154     7.3355     0.0000      0.0825      0.1429
exper           0.0214     0.0154     1.3929     0.1644     -0.0088      0.0517
hours           0.0002     0.0002     0.7707     0.4413     -0.0003      0.0007
======================
     Instruments
----------------------
age, kidslt6, nwifeinc
----------------------

Covariance Estimator:
Homoskedastic (Unadjusted) Covariance (Debiased: True, GLS: True)
SystemResults, id: 0x14aee5c56d0