# For Loops: Interest Rates

There are two ways to solve problems: analytically and computationally. Most of us have been trained to solve problems analtyically. For example, when you solve a system of equations, you find the price point or points where the lines of interest intersect. Perhaps you are attepmting to solve for the quantity of production that will maximaize profits for a firm, so you set up a Lagangian. While analytic solutions are indispensable, it often makes sense to solve problems computationally. Sometimes, this means performing a series of operations that are prestated. For example, you can compound interest over $t$ periods instead of raising $(1+r)^t$. In essence, these result in the same thing, so this is the boring case. In the more interesting cases, computation allows us to *guess and check*. We could, for example, use computational methods to find which interest yields a particular future value by marginally increasing the interest rate when the future value is smaller than the target and decreasing the rate when it is larger than the target. Artificial intelligence uses this *guess and check* method (sometimes referred to as *brute force*). This method may be used in combination with the first method.

In this lesson, we will introduce for loops to understand their role in developing computational solutions to problems.

## For Loops

First, we must develop our understanding of for loops. We can think of for loops as a means of counting. The command *__for i in range(n)__* will count from i to n - 1. Let's get started by counting.

In [2]:
# counting with a for loop

for i in range(10, 100):
    print(i, end = ", ") # by default, end = "\n"
range_list = list(range(10,101))
for i in range_list:
    print(i, end = ", ")

10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100,

Next let's create lists using for loops. There are many ways to create a list and many ways to count. 

You may create a list with values entered individually.

In [3]:
# create a list by entering values individually
lst1 = [0,1,2,3,4,5]
print(lst1)

[0, 1, 2, 3, 4, 5]

You can create empty lists and fill them with values as they appear within a for loop using append or insert().

The method *.append(obj)* adds an element to the end of the list. The method *.insert(obj, index)* adds a new value to the list. The equivalent of *lst.append(obj)* is *lst.insert(obj, -1)*.

In [12]:
# Create empty list and fill using a for loop
lst2 = []
# count by ones to 100
for i in range(101):
    lst2.append(i)
    
lst3 = []
# count by twos
for i in range(0, 101, 2):
    lst3.append(i)
lst4 = []
# create list of numbers from 0 to 100
for i in range(101):
    lst4.insert(i, i)
    
# Create a list of number that moves backwards from 100 to 0.
lst5 = []
for i in range(101):
    lst5.insert(0, i)
print(lst2)
print(lst3)
print(lst4)
print(lst5)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100]
[100, 99, 98, 97, 96, 95, 94, 93, 92, 91, 90, 89, 88, 87, 86, 85, 84, 83, 82, 81, 80, 79, 78, 77, 76, 75, 74, 73, 72, 71, 70, 69, 68, 67, 66, 65, 64, 63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0]

Or you may pass a for loop to the *list()* function.

In [15]:
# create list counting by twos using list(range())
lst6 = list(range(0,101,2))
# counting backward
lst7 = list(range(50, -1, -2))
print(lst6)
print(lst7)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100]
[50, 48, 46, 44, 42, 40, 38, 36, 34, 32, 30, 28, 26, 24, 22, 20, 18, 16, 14, 12, 10, 8, 6, 4, 2, 0]

Finally, you may use a generator, which takes the form _[i for i in range(n)]_.

In [16]:
lst8 = [i for i in range(100,-1, -1)]
print(lst8)

[100, 99, 98, 97, 96, 95, 94, 93, 92, 91, 90, 89, 88, 87, 86, 85, 84, 83, 82, 81, 80, 79, 78, 77, 76, 75, 74, 73, 72, 71, 70, 69, 68, 67, 66, 65, 64, 63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0]

Let's print all of the lists that we have created, and name each of them as we print them. We pass the argument, sep = "\n" to print the list on the line that follows its label.

In [17]:
print("lst1:", lst1, sep = "\n")
print("lst2:", lst2, sep = "\n")
print("lst3:", lst3, sep = "\n")
print("lst4:", lst4, sep = "\n")
print("lst5:", lst5, sep = "\n")
print("lst6:", lst6, sep = "\n")
print("lst6:", lst7, sep = "\n")
print("lst6:", lst8, sep = "\n")

lst1:
[0, 1, 2, 3, 4, 5]
lst2:
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100]
lst3:
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100]
lst4:
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100]
lst5:
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100]
lst6:
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100]
lst6:
[50, 48, 46, 44, 42, 40, 38, 36, 34, 32, 30, 28, 26, 24, 22, 20, 18, 16, 14, 12, 10, 8, 6, 4, 2, 0]
lst6:
[100, 99, 98, 97, 96, 95, 94, 93, 92, 91, 90, 89, 88, 87, 86, 85, 84, 83, 82, 81, 80, 79, 78, 77, 76, 75, 74, 73, 72, 71, 70, 69, 68, 67, 66, 65, 64, 63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0]

We will use for loops in the later examples. Lists will reappear in later lessons and are important for understanding the statistical functions in chapter 3.

## Calculating Interest Earned

The present value equation relates the interest rate with the value of principal to produce the present value after some number of periods:

$FV = PV(1+r)^t$

In this form, the interest rate, $r$, is given for a single period, with $t$ denoting the number of periods the principle is compounded by interest. 

We can use the given formula to solve for any variable. In this case, Python is just acting as a calculator. Let's solve for the interest rate given the values of the other variables.

$FV = PV(1+r)^t$

$(1+r)^t = \frac{FV}{PV}$

$1+r = (\frac{FV}{PV})^{1/t}$

$r = (\frac{FV}{PV})^{1/t}-1$

Suppose that two years after you place 1000 dollars in a deposit account, the value of the deposit grows to 1200 dollars. Build python script that calculates the annual interest rate.

In [37]:
r = (1200 / 1000) ** (1/2) - 1
r

0.09544511501033215

In [40]:
1000 * (1 + r) ** 2

1199.9999999999998

Now let's use a for loop to calculate the future value of the 1000 dollar deposit after 1 year given an interest rate of 10% and compounding over n periods within the year. Test for semi-annual, quarterly, monthly, weekly, and daily compounding.

$FV = PV(1+\frac{r}{n})^{tn}$

In [4]:
# for i in range(t): compound interest, then multiply by principle.
compounding_def = {"annual":1,
                   "semi-annual":2,
                   "quarterly":4,
                   "monthly":12,
                   "weekly":52,
                   "daily":365
                  }
compounding_interest = {.1:{}}
for period_name, n in compounding_def.items():
    compounding_interest[period_name]= round(1000 * (1 + .1 / n) ** (1 * n), 2)
compounding_interest

{0.1: {},
 'annual': 1100.0,
 'semi-annual': 1102.5,
 'quarterly': 1103.81,
 'monthly': 1104.71,
 'weekly': 1105.06,
 'daily': 1105.16}

Now let's use a for loop to calculate these the future value of deposits for interest rates from 1% to 20%.

In [5]:
# for i in range(t): compound interest, then multiply by principle.
compounding_def = {"annual":1,
                   "semi-annual":2,
                   "quarterly":4,
                   "monthly":12,
                   "weekly":52,
                   "daily":365
                  }
rates = [i for i in range(1,21)]
compounding_interest = {}
for rate in rates:
    r = rate / 100
    rate = str(rate)+"%"
    compounding_interest[rate] = {}
    for period_name, n in compounding_def.items():
        compounding_interest[rate][period_name]=round(1000 * (1 + r / n) ** (1 * n), 2)

compounding_interest

{'1%': {'annual': 1010.0,
  'semi-annual': 1010.02,
  'quarterly': 1010.04,
  'monthly': 1010.05,
  'weekly': 1010.05,
  'daily': 1010.05},
 '2%': {'annual': 1020.0,
  'semi-annual': 1020.1,
  'quarterly': 1020.15,
  'monthly': 1020.18,
  'weekly': 1020.2,
  'daily': 1020.2},
 '3%': {'annual': 1030.0,
  'semi-annual': 1030.22,
  'quarterly': 1030.34,
  'monthly': 1030.42,
  'weekly': 1030.45,
  'daily': 1030.45},
 '4%': {'annual': 1040.0,
  'semi-annual': 1040.4,
  'quarterly': 1040.6,
  'monthly': 1040.74,
  'weekly': 1040.79,
  'daily': 1040.81},
 '5%': {'annual': 1050.0,
  'semi-annual': 1050.62,
  'quarterly': 1050.95,
  'monthly': 1051.16,
  'weekly': 1051.25,
  'daily': 1051.27},
 '6%': {'annual': 1060.0,
  'semi-annual': 1060.9,
  'quarterly': 1061.36,
  'monthly': 1061.68,
  'weekly': 1061.8,
  'daily': 1061.83},
 '7%': {'annual': 1070.0,
  'semi-annual': 1071.22,
  'quarterly': 1071.86,
  'monthly': 1072.29,
  'weekly': 1072.46,
  'daily': 1072.5},
 '8%': {'annual': 1080.0,
  'semi-annual': 1081.6,
  'quarterly': 1082.43,
  'monthly': 1083.0,
  'weekly': 1083.22,
  'daily': 1083.28},
 '9%': {'annual': 1090.0,
  'semi-annual': 1092.02,
  'quarterly': 1093.08,
  'monthly': 1093.81,
  'weekly': 1094.09,
  'daily': 1094.16},
 '10%': {'annual': 1100.0,
  'semi-annual': 1102.5,
  'quarterly': 1103.81,
  'monthly': 1104.71,
  'weekly': 1105.06,
  'daily': 1105.16},
 '11%': {'annual': 1110.0,
  'semi-annual': 1113.02,
  'quarterly': 1114.62,
  'monthly': 1115.72,
  'weekly': 1116.15,
  'daily': 1116.26},
 '12%': {'annual': 1120.0,
  'semi-annual': 1123.6,
  'quarterly': 1125.51,
  'monthly': 1126.83,
  'weekly': 1127.34,
  'daily': 1127.47},
 '13%': {'annual': 1130.0,
  'semi-annual': 1134.22,
  'quarterly': 1136.48,
  'monthly': 1138.03,
  'weekly': 1138.64,
  'daily': 1138.8},
 '14%': {'annual': 1140.0,
  'semi-annual': 1144.9,
  'quarterly': 1147.52,
  'monthly': 1149.34,
  'weekly': 1150.06,
  'daily': 1150.24},
 '15%': {'annual': 1150.0,
  'semi-annual': 1155.62,
  'quarterly': 1158.65,
  'monthly': 1160.75,
  'weekly': 1161.58,
  'daily': 1161.8},
 '16%': {'annual': 1160.0,
  'semi-annual': 1166.4,
  'quarterly': 1169.86,
  'monthly': 1172.27,
  'weekly': 1173.22,
  'daily': 1173.47},
 '17%': {'annual': 1170.0,
  'semi-annual': 1177.22,
  'quarterly': 1181.15,
  'monthly': 1183.89,
  'weekly': 1184.98,
  'daily': 1185.26},
 '18%': {'annual': 1180.0,
  'semi-annual': 1188.1,
  'quarterly': 1192.52,
  'monthly': 1195.62,
  'weekly': 1196.85,
  'daily': 1197.16},
 '19%': {'annual': 1190.0,
  'semi-annual': 1199.03,
  'quarterly': 1203.97,
  'monthly': 1207.45,
  'weekly': 1208.83,
  'daily': 1209.19},
 '20%': {'annual': 1200.0,
  'semi-annual': 1210.0,
  'quarterly': 1215.51,
  'monthly': 1219.39,
  'weekly': 1220.93,
  'daily': 1221.34}}

Finally, create a dataframe of the dictionary.

In [6]:
import pandas as pd
compounding_interest_df = pd.DataFrame(compounding_interest, index = compounding_interest["1%"].keys())
compounding_interest_df.index.name = "Compounding per Year"
compounding_interest_df

,1%,2%,3%,4%,5%,6%,7%,8%,9%,10%,11%,12%,13%,14%,15%,16%,17%,18%,19%,20%
Compounding per Year,,,,,,,,,,,,,,,,,,,,
annual,1010.00,1020.00,1030.00,1040.00,1050.00,1060.00,1070.00,1080.00,1090.00,1100.00,1110.00,1120.00,1130.00,1140.00,1150.00,1160.00,1170.00,1180.00,1190.00,1200.00
semi-annual,1010.02,1020.10,1030.22,1040.40,1050.62,1060.90,1071.22,1081.60,1092.02,1102.50,1113.02,1123.60,1134.22,1144.90,1155.62,1166.40,1177.22,1188.10,1199.03,1210.00
quarterly,1010.04,1020.15,1030.34,1040.60,1050.95,1061.36,1071.86,1082.43,1093.08,1103.81,1114.62,1125.51,1136.48,1147.52,1158.65,1169.86,1181.15,1192.52,1203.97,1215.51
monthly,1010.05,1020.18,1030.42,1040.74,1051.16,1061.68,1072.29,1083.00,1093.81,1104.71,1115.72,1126.83,1138.03,1149.34,1160.75,1172.27,1183.89,1195.62,1207.45,1219.39
weekly,1010.05,1020.20,1030.45,1040.79,1051.25,1061.80,1072.46,1083.22,1094.09,1105.06,1116.15,1127.34,1138.64,1150.06,1161.58,1173.22,1184.98,1196.85,1208.83,1220.93
daily,1010.05,1020.20,1030.45,1040.81,1051.27,1061.83,1072.50,1083.28,1094.16,1105.16,1116.26,1127.47,1138.80,1150.24,1161.80,1173.47,1185.26,1197.16,1209.19,1221.34

Use the method, *df.T*, to transpose the dataframe. This will switch the index and column names.

In [7]:
compounding_interest_df.T

Compounding per Year,annual,semi-annual,quarterly,monthly,weekly,daily
1%,1010.0,1010.02,1010.04,1010.05,1010.05,1010.05
2%,1020.0,1020.10,1020.15,1020.18,1020.20,1020.20
3%,1030.0,1030.22,1030.34,1030.42,1030.45,1030.45
4%,1040.0,1040.40,1040.60,1040.74,1040.79,1040.81
5%,1050.0,1050.62,1050.95,1051.16,1051.25,1051.27
6%,1060.0,1060.90,1061.36,1061.68,1061.80,1061.83
7%,1070.0,1071.22,1071.86,1072.29,1072.46,1072.50
8%,1080.0,1081.60,1082.43,1083.00,1083.22,1083.28
9%,1090.0,1092.02,1093.08,1093.81,1094.09,1094.16
10%,1100.0,1102.50,1103.81,1104.71,1105.06,1105.16
11%,1110.0,1113.02,1114.62,1115.72,1116.15,1116.26
12%,1120.0,1123.60,1125.51,1126.83,1127.34,1127.47
13%,1130.0,1134.22,1136.48,1138.03,1138.64,1138.80
14%,1140.0,1144.90,1147.52,1149.34,1150.06,1150.24
15%,1150.0,1155.62,1158.65,1160.75,1161.58,1161.80
16%,1160.0,1166.40,1169.86,1172.27,1173.22,1173.47
17%,1170.0,1177.22,1181.15,1183.89,1184.98,1185.26
18%,1180.0,1188.10,1192.52,1195.62,1196.85,1197.16
19%,1190.0,1199.03,1203.97,1207.45,1208.83,1209.19
20%,1200.0,1210.00,1215.51,1219.39,1220.93,1221.34

## Using computational methods to brute force solve for a value

The *guess and check* method was probably given a bad rap by your high scholl algebra teacher. It is a rather costly way to approximate solutions for math problems when computing is costly - say, when you have only paper and pencil at your disposal. However, when computational resources are especially cheap, as they are now, the "guess and check" method is often the best way to find a solution. Those of you who have taken courses in advanced mathematics might even be familiar with problems where there exist no analytical solution at all. In this case, the only suitable method for finding a solution is to *guess and check*. 

To solve by brute force, we will first need to review *if statements*. An *if statement* checks if a particualr statement is True. If it is, it runs the block of code indented in the lines that follow it. Let's run through a few examples.

In [8]:
x = True
if x == True:
    print(x)
else:
    print("x is not True")

True

In [9]:
x = False
if x == True:
    print(x)
else:
    print("x is not True")

x is not True

In [10]:
x = 100
if x == True:
    print(x)
else:
    print("x is not True")

x is not True

If statements are useful for checking the value of a variable. For example, we may want to now if x is less than, equal to, or greater than some value.

In [11]:
x = 3
if x < 3:
    print("x =",x,"which is less than 3")
elif x == 3:
    print("x =",x,"which is equal to 3")
elif x > 3:
    print("x =",x,"which is greater than 3")

x = 3 which is equal to 3

We can also use if statements to moderate the value of a variable. Suppose that we want to keep multiplying a variable by an unknwon number to compute a particular product. For example, we can solve 3x = 15 analytically since x = 15 / 3:

In [12]:
x = 15/3
print("x =", x)

x = 5.0

But suppose we wanted to create a program where the computer solves this task itself. There are surely many ways to accomplish this. Let's train the computer to solve this problem. Let's solve for 

$ax = 15$ where $a = 3$.

In [13]:
a = 3
x = 1
while a * x != 15:
    x = x + 1
    print("x =",x,"\tax=",a*x)
print("Solution for 3x = 15:", x)

x = 2 	ax= 6
x = 3 	ax= 9
x = 4 	ax= 12
x = 5 	ax= 15
Solution for 3x = 15: 5

This was easy for products that yield integers, but what if the product is a fraction or factors to include a fraction? In this case, we will want to teach the computer to decrease the margin of change. We will have to add variables to the system to keep track of its state, namely the value of ax. When ax is below 1000 we will increase x. When ax is above 1000, we will decrease x. Every time ax cross 1000, we will decrease the absolute value of the the margin of change by a factor of 10.

Let's solve for ax = 1000 to the 10th decimal place.

In [17]:
a = 3
x = 1
ax = a * x
# margin must be float
margin = 1.0
# create variable to track if ax is above or below 1000
below_1000 = True
# create variable that decrease rate of change of x every time ax cross 1000
decrease_margin = False

while round(ax, 10) != 1000:
    if decrease_margin: 
        margin = margin * .1
        decrease_margin = False
    
    x = x + margin if ax < 1000 else x - margin
    print("x =",x,"\tax=",a*x)    
    # redefine ax with new x value
    ax = a * x
    if below_1000 == True and ax > 1000: 
        decrease_margin = True
        below_1000 = False
    elif below_1000 == False and ax < 1000: 
        decrease_margin = True
        below_1000 = True
print("Solution: ("+str(a)+")"+"("+str(x)+") =", ax)

x = 2.0 	ax= 6.0
x = 3.0 	ax= 9.0
x = 4.0 	ax= 12.0
x = 5.0 	ax= 15.0
x = 6.0 	ax= 18.0
x = 7.0 	ax= 21.0
x = 8.0 	ax= 24.0
x = 9.0 	ax= 27.0
x = 10.0 	ax= 30.0
x = 11.0 	ax= 33.0
x = 12.0 	ax= 36.0
x = 13.0 	ax= 39.0
x = 14.0 	ax= 42.0
x = 15.0 	ax= 45.0
x = 16.0 	ax= 48.0
x = 17.0 	ax= 51.0
x = 18.0 	ax= 54.0
x = 19.0 	ax= 57.0
x = 20.0 	ax= 60.0
x = 21.0 	ax= 63.0
x = 22.0 	ax= 66.0
x = 23.0 	ax= 69.0
x = 24.0 	ax= 72.0
x = 25.0 	ax= 75.0
x = 26.0 	ax= 78.0
x = 27.0 	ax= 81.0
x = 28.0 	ax= 84.0
x = 29.0 	ax= 87.0
x = 30.0 	ax= 90.0
x = 31.0 	ax= 93.0
x = 32.0 	ax= 96.0
x = 33.0 	ax= 99.0
x = 34.0 	ax= 102.0
x = 35.0 	ax= 105.0
x = 36.0 	ax= 108.0
x = 37.0 	ax= 111.0
x = 38.0 	ax= 114.0
x = 39.0 	ax= 117.0
x = 40.0 	ax= 120.0
x = 41.0 	ax= 123.0
x = 42.0 	ax= 126.0
x = 43.0 	ax= 129.0
x = 44.0 	ax= 132.0
x = 45.0 	ax= 135.0
x = 46.0 	ax= 138.0
x = 47.0 	ax= 141.0
x = 48.0 	ax= 144.0
x = 49.0 	ax= 147.0
x = 50.0 	ax= 150.0
x = 51.0 	ax= 153.0
x = 52.0 	ax= 156.0
x = 53.0 	ax= 159.0
x = 54.0 	ax= 162.0
x = 55.0 	ax= 165.0
x = 56.0 	ax= 168.0
x = 57.0 	ax= 171.0
x = 58.0 	ax= 174.0
x = 59.0 	ax= 177.0
x = 60.0 	ax= 180.0
x = 61.0 	ax= 183.0
x = 62.0 	ax= 186.0
x = 63.0 	ax= 189.0
x = 64.0 	ax= 192.0
x = 65.0 	ax= 195.0
x = 66.0 	ax= 198.0
x = 67.0 	ax= 201.0
x = 68.0 	ax= 204.0
x = 69.0 	ax= 207.0
x = 70.0 	ax= 210.0
x = 71.0 	ax= 213.0
x = 72.0 	ax= 216.0
x = 73.0 	ax= 219.0
x = 74.0 	ax= 222.0
x = 75.0 	ax= 225.0
x = 76.0 	ax= 228.0
x = 77.0 	ax= 231.0
x = 78.0 	ax= 234.0
x = 79.0 	ax= 237.0
x = 80.0 	ax= 240.0
x = 81.0 	ax= 243.0
x = 82.0 	ax= 246.0
x = 83.0 	ax= 249.0
x = 84.0 	ax= 252.0
x = 85.0 	ax= 255.0
x = 86.0 	ax= 258.0
x = 87.0 	ax= 261.0
x = 88.0 	ax= 264.0
x = 89.0 	ax= 267.0
x = 90.0 	ax= 270.0
x = 91.0 	ax= 273.0
x = 92.0 	ax= 276.0
x = 93.0 	ax= 279.0
x = 94.0 	ax= 282.0
x = 95.0 	ax= 285.0
x = 96.0 	ax= 288.0
x = 97.0 	ax= 291.0
x = 98.0 	ax= 294.0
x = 99.0 	ax= 297.0
x = 100.0 	ax= 300.0
x = 101.0 	ax= 303.0
x = 102.0 	ax= 306.0
x = 103.0 	ax= 309.0
x = 104.0 	ax= 312.0
x = 105.0 	ax= 315.0
x = 106.0 	ax= 318.0
x = 107.0 	ax= 321.0
x = 108.0 	ax= 324.0
x = 109.0 	ax= 327.0
x = 110.0 	ax= 330.0
x = 111.0 	ax= 333.0
x = 112.0 	ax= 336.0
x = 113.0 	ax= 339.0
x = 114.0 	ax= 342.0
x = 115.0 	ax= 345.0
x = 116.0 	ax= 348.0
x = 117.0 	ax= 351.0
x = 118.0 	ax= 354.0
x = 119.0 	ax= 357.0
x = 120.0 	ax= 360.0
x = 121.0 	ax= 363.0
x = 122.0 	ax= 366.0
x = 123.0 	ax= 369.0
x = 124.0 	ax= 372.0
x = 125.0 	ax= 375.0
x = 126.0 	ax= 378.0
x = 127.0 	ax= 381.0
x = 128.0 	ax= 384.0
x = 129.0 	ax= 387.0
x = 130.0 	ax= 390.0
x = 131.0 	ax= 393.0
x = 132.0 	ax= 396.0
x = 133.0 	ax= 399.0
x = 134.0 	ax= 402.0
x = 135.0 	ax= 405.0
x = 136.0 	ax= 408.0
x = 137.0 	ax= 411.0
x = 138.0 	ax= 414.0
x = 139.0 	ax= 417.0
x = 140.0 	ax= 420.0
x = 141.0 	ax= 423.0
x = 142.0 	ax= 426.0
x = 143.0 	ax= 429.0
x = 144.0 	ax= 432.0
x = 145.0 	ax= 435.0
x = 146.0 	ax= 438.0
x = 147.0 	ax= 441.0
x = 148.0 	ax= 444.0
x = 149.0 	ax= 447.0
x = 150.0 	ax= 450.0
x = 151.0 	ax= 453.0
x = 152.0 	ax= 456.0
x = 153.0 	ax= 459.0
x = 154.0 	ax= 462.0
x = 155.0 	ax= 465.0
x = 156.0 	ax= 468.0
x = 157.0 	ax= 471.0
x = 158.0 	ax= 474.0
x = 159.0 	ax= 477.0
x = 160.0 	ax= 480.0
x = 161.0 	ax= 483.0
x = 162.0 	ax= 486.0
x = 163.0 	ax= 489.0
x = 164.0 	ax= 492.0
x = 165.0 	ax= 495.0
x = 166.0 	ax= 498.0
x = 167.0 	ax= 501.0
x = 168.0 	ax= 504.0
x = 169.0 	ax= 507.0
x = 170.0 	ax= 510.0
x = 171.0 	ax= 513.0
x = 172.0 	ax= 516.0
x = 173.0 	ax= 519.0
x = 174.0 	ax= 522.0
x = 175.0 	ax= 525.0
x = 176.0 	ax= 528.0
x = 177.0 	ax= 531.0
x = 178.0 	ax= 534.0
x = 179.0 	ax= 537.0
x = 180.0 	ax= 540.0
x = 181.0 	ax= 543.0
x = 182.0 	ax= 546.0
x = 183.0 	ax= 549.0
x = 184.0 	ax= 552.0
x = 185.0 	ax= 555.0
x = 186.0 	ax= 558.0
x = 187.0 	ax= 561.0
x = 188.0 	ax= 564.0
x = 189.0 	ax= 567.0
x = 190.0 	ax= 570.0
x = 191.0 	ax= 573.0
x = 192.0 	ax= 576.0
x = 193.0 	ax= 579.0
x = 194.0 	ax= 582.0
x = 195.0 	ax= 585.0
x = 196.0 	ax= 588.0
x = 197.0 	ax= 591.0
x = 198.0 	ax= 594.0
x = 199.0 	ax= 597.0
x = 200.0 	ax= 600.0
x = 201.0 	ax= 603.0
x = 202.0 	ax= 606.0
x = 203.0 	ax= 609.0
x = 204.0 	ax= 612.0
x = 205.0 	ax= 615.0
x = 206.0 	ax= 618.0
x = 207.0 	ax= 621.0
x = 208.0 	ax= 624.0
x = 209.0 	ax= 627.0
x = 210.0 	ax= 630.0
x = 211.0 	ax= 633.0
x = 212.0 	ax= 636.0
x = 213.0 	ax= 639.0
x = 214.0 	ax= 642.0
x = 215.0 	ax= 645.0
x = 216.0 	ax= 648.0
x = 217.0 	ax= 651.0
x = 218.0 	ax= 654.0
x = 219.0 	ax= 657.0
x = 220.0 	ax= 660.0
x = 221.0 	ax= 663.0
x = 222.0 	ax= 666.0
x = 223.0 	ax= 669.0
x = 224.0 	ax= 672.0
x = 225.0 	ax= 675.0
x = 226.0 	ax= 678.0
x = 227.0 	ax= 681.0
x = 228.0 	ax= 684.0
x = 229.0 	ax= 687.0
x = 230.0 	ax= 690.0
x = 231.0 	ax= 693.0
x = 232.0 	ax= 696.0
x = 233.0 	ax= 699.0
x = 234.0 	ax= 702.0
x = 235.0 	ax= 705.0
x = 236.0 	ax= 708.0
x = 237.0 	ax= 711.0
x = 238.0 	ax= 714.0
x = 239.0 	ax= 717.0
x = 240.0 	ax= 720.0
x = 241.0 	ax= 723.0
x = 242.0 	ax= 726.0
x = 243.0 	ax= 729.0
x = 244.0 	ax= 732.0
x = 245.0 	ax= 735.0
x = 246.0 	ax= 738.0
x = 247.0 	ax= 741.0
x = 248.0 	ax= 744.0
x = 249.0 	ax= 747.0
x = 250.0 	ax= 750.0
x = 251.0 	ax= 753.0
x = 252.0 	ax= 756.0
x = 253.0 	ax= 759.0
x = 254.0 	ax= 762.0
x = 255.0 	ax= 765.0
x = 256.0 	ax= 768.0
x = 257.0 	ax= 771.0
x = 258.0 	ax= 774.0
x = 259.0 	ax= 777.0
x = 260.0 	ax= 780.0
x = 261.0 	ax= 783.0
x = 262.0 	ax= 786.0
x = 263.0 	ax= 789.0
x = 264.0 	ax= 792.0
x = 265.0 	ax= 795.0
x = 266.0 	ax= 798.0
x = 267.0 	ax= 801.0
x = 268.0 	ax= 804.0
x = 269.0 	ax= 807.0
x = 270.0 	ax= 810.0
x = 271.0 	ax= 813.0
x = 272.0 	ax= 816.0
x = 273.0 	ax= 819.0
x = 274.0 	ax= 822.0
x = 275.0 	ax= 825.0
x = 276.0 	ax= 828.0
x = 277.0 	ax= 831.0
x = 278.0 	ax= 834.0
x = 279.0 	ax= 837.0
x = 280.0 	ax= 840.0
x = 281.0 	ax= 843.0
x = 282.0 	ax= 846.0
x = 283.0 	ax= 849.0
x = 284.0 	ax= 852.0
x = 285.0 	ax= 855.0
x = 286.0 	ax= 858.0
x = 287.0 	ax= 861.0
x = 288.0 	ax= 864.0
x = 289.0 	ax= 867.0
x = 290.0 	ax= 870.0
x = 291.0 	ax= 873.0
x = 292.0 	ax= 876.0
x = 293.0 	ax= 879.0
x = 294.0 	ax= 882.0
x = 295.0 	ax= 885.0
x = 296.0 	ax= 888.0
x = 297.0 	ax= 891.0
x = 298.0 	ax= 894.0
x = 299.0 	ax= 897.0
x = 300.0 	ax= 900.0
x = 301.0 	ax= 903.0
x = 302.0 	ax= 906.0
x = 303.0 	ax= 909.0
x = 304.0 	ax= 912.0
x = 305.0 	ax= 915.0
x = 306.0 	ax= 918.0
x = 307.0 	ax= 921.0
x = 308.0 	ax= 924.0
x = 309.0 	ax= 927.0
x = 310.0 	ax= 930.0
x = 311.0 	ax= 933.0
x = 312.0 	ax= 936.0
x = 313.0 	ax= 939.0
x = 314.0 	ax= 942.0
x = 315.0 	ax= 945.0
x = 316.0 	ax= 948.0
x = 317.0 	ax= 951.0
x = 318.0 	ax= 954.0
x = 319.0 	ax= 957.0
x = 320.0 	ax= 960.0
x = 321.0 	ax= 963.0
x = 322.0 	ax= 966.0
x = 323.0 	ax= 969.0
x = 324.0 	ax= 972.0
x = 325.0 	ax= 975.0
x = 326.0 	ax= 978.0
x = 327.0 	ax= 981.0
x = 328.0 	ax= 984.0
x = 329.0 	ax= 987.0
x = 330.0 	ax= 990.0
x = 331.0 	ax= 993.0
x = 332.0 	ax= 996.0
x = 333.0 	ax= 999.0
x = 334.0 	ax= 1002.0
x = 333.9 	ax= 1001.6999999999999
x = 333.79999999999995 	ax= 1001.3999999999999
x = 333.69999999999993 	ax= 1001.0999999999998
x = 333.5999999999999 	ax= 1000.7999999999997
x = 333.4999999999999 	ax= 1000.4999999999997
x = 333.39999999999986 	ax= 1000.1999999999996
x = 333.29999999999984 	ax= 999.8999999999995
x = 333.30999999999983 	ax= 999.9299999999995
x = 333.3199999999998 	ax= 999.9599999999995
x = 333.3299999999998 	ax= 999.9899999999994
x = 333.3399999999998 	ax= 1000.0199999999994
x = 333.3389999999998 	ax= 1000.0169999999995
x = 333.33799999999985 	ax= 1000.0139999999996
x = 333.3369999999999 	ax= 1000.0109999999996
x = 333.3359999999999 	ax= 1000.0079999999997
x = 333.3349999999999 	ax= 1000.0049999999998
x = 333.33399999999995 	ax= 1000.0019999999998
x = 333.33299999999997 	ax= 999.9989999999999
x = 333.33309999999994 	ax= 999.9992999999998
x = 333.3331999999999 	ax= 999.9995999999998
x = 333.3332999999999 	ax= 999.9998999999997
x = 333.33339999999987 	ax= 1000.0001999999996
x = 333.3333899999999 	ax= 1000.0001699999997
x = 333.3333799999999 	ax= 1000.0001399999998
x = 333.33336999999995 	ax= 1000.0001099999998
x = 333.33335999999997 	ax= 1000.0000799999999
x = 333.33335 	ax= 1000.00005
x = 333.33334 	ax= 1000.0000200000001
x = 333.33333000000005 	ax= 999.9999900000001
x = 333.33333100000004 	ax= 999.9999930000001
x = 333.33333200000004 	ax= 999.9999960000001
x = 333.33333300000004 	ax= 999.9999990000001
x = 333.33333400000004 	ax= 1000.0000020000001
x = 333.3333339 	ax= 1000.0000017
x = 333.3333338 	ax= 1000.0000014
x = 333.33333369999997 	ax= 1000.0000011
x = 333.33333359999995 	ax= 1000.0000007999998
x = 333.3333334999999 	ax= 1000.0000004999997
x = 333.3333333999999 	ax= 1000.0000001999997
x = 333.3333332999999 	ax= 999.9999998999997
x = 333.3333333099999 	ax= 999.9999999299996
x = 333.3333333199999 	ax= 999.9999999599997
x = 333.3333333299999 	ax= 999.9999999899997
x = 333.3333333399999 	ax= 1000.0000000199998
x = 333.3333333389999 	ax= 1000.0000000169998
x = 333.33333333799993 	ax= 1000.0000000139999
x = 333.33333333699994 	ax= 1000.0000000109999
x = 333.33333333599995 	ax= 1000.0000000079999
x = 333.33333333499996 	ax= 1000.000000005
x = 333.333333334 	ax= 1000.000000002
x = 333.333333333 	ax= 999.999999999
x = 333.3333333331 	ax= 999.9999999992999
x = 333.33333333319996 	ax= 999.9999999995998
x = 333.33333333329995 	ax= 999.9999999998998
x = 333.33333333339993 	ax= 1000.0000000001999
x = 333.33333333338993 	ax= 1000.0000000001698
x = 333.3333333333799 	ax= 1000.0000000001398
x = 333.3333333333699 	ax= 1000.0000000001098
x = 333.3333333333599 	ax= 1000.0000000000798
x = 333.3333333333499 	ax= 1000.0000000000498
Solution: (3)(333.3333333333499) = 1000.0000000000498

## Use brute force to solve for the interest rate you would need to grow 1000 to 1500 after 2 years of annual compounding?

In [15]:
PV = 1000
FV = 1000
r = .01
margin = .01
below_1500 = True
decrease_margin = False
while round(FV,2) != 1500.00:
    if decrease_margin: 
        margin = margin * .1
        decrease_margin = False
    r = r + margin if FV < 1500 else r - margin
    FV = PV * (1 + r) ** 2
    print("r:",r,"\tFV:", FV)
    if below_1500 == True and FV > 1500: 
        decrease_margin = True
        below_1500 = False
    elif below_1500 == False and FV < 1500: 
        decrease_margin = True
        below_1500 = True

r: 0.02 	FV: 1040.4
r: 0.03 	FV: 1060.8999999999999
r: 0.04 	FV: 1081.6000000000001
r: 0.05 	FV: 1102.5
r: 0.060000000000000005 	FV: 1123.6000000000001
r: 0.07 	FV: 1144.9
r: 0.08 	FV: 1166.4
r: 0.09 	FV: 1188.1000000000001
r: 0.09999999999999999 	FV: 1210.0000000000002
r: 0.10999999999999999 	FV: 1232.0999999999997
r: 0.11999999999999998 	FV: 1254.3999999999996
r: 0.12999999999999998 	FV: 1276.8999999999996
r: 0.13999999999999999 	FV: 1299.6
r: 0.15 	FV: 1322.4999999999998
r: 0.16 	FV: 1345.6
r: 0.17 	FV: 1368.8999999999999
r: 0.18000000000000002 	FV: 1392.3999999999999
r: 0.19000000000000003 	FV: 1416.1
r: 0.20000000000000004 	FV: 1440.0
r: 0.21000000000000005 	FV: 1464.1
r: 0.22000000000000006 	FV: 1488.3999999999999
r: 0.23000000000000007 	FV: 1512.8999999999999
r: 0.22900000000000006 	FV: 1510.4410000000003
r: 0.22800000000000006 	FV: 1507.984
r: 0.22700000000000006 	FV: 1505.5290000000002
r: 0.22600000000000006 	FV: 1503.0759999999998
r: 0.22500000000000006 	FV: 1500.6250000000002
r: 0.22400000000000006 	FV: 1498.176
r: 0.22410000000000005 	FV: 1498.4208099999998
r: 0.22420000000000004 	FV: 1498.6656399999997
r: 0.22430000000000003 	FV: 1498.91049
r: 0.22440000000000002 	FV: 1499.1553599999997
r: 0.2245 	FV: 1499.40025
r: 0.2246 	FV: 1499.6451599999998
r: 0.22469999999999998 	FV: 1499.8900899999999
r: 0.22479999999999997 	FV: 1500.1350399999997
r: 0.22478999999999996 	FV: 1500.1105441000002
r: 0.22477999999999995 	FV: 1500.0860484
r: 0.22476999999999994 	FV: 1500.0615529
r: 0.22475999999999993 	FV: 1500.0370575999998
r: 0.22474999999999992 	FV: 1500.0125625
r: 0.2247399999999999 	FV: 1499.9880676
r: 0.2247409999999999 	FV: 1499.9905170809998
r: 0.22474199999999991 	FV: 1499.992966564
r: 0.22474299999999992 	FV: 1499.995416049

### Now use a dictionary and brute force to solve for the interest rate you would need to grow 1000 to each value from 1100 to 2000 after 2 years of annual compounding?

In [16]:
PV = 1000
FV = 1000
r = .01
margin = .01
FV_dict = {}
for final_FV in range(1100, 2001, 100):                            
    below_final_FV = True
    decrease_margin = False
    while round(FV,2) != final_FV:
        if decrease_margin: 
            margin = margin * .1
            decrease_margin = False
        r = r + margin if FV < final_FV else r - margin
        FV = PV * (1 + r) ** 2
        if below_final_FV == True and FV > final_FV: 
            decrease_margin = True
            below_final_FV = False
        elif below_final_FV == False and FV < final_FV: 
            decrease_margin = True
            below_final_FV = True
    # once the program breaks out of the while loop, save the solution
    FV_dict[final_FV] = r
# check that solutions are saved in dictionary
FV_dict

{1100: 0.04881,
 1200: 0.09544699999999141,
 1300: 0.14017400000003613,
 1400: 0.18321400000007917,
 1500: 0.2247430000001207,
 1600: 0.264909999999747,
 1700: 0.30383899999870545,
 1800: 0.3416389999976941,
 1900: 0.3784039999967104,
 2000: 0.41421199999575237}

Now that we have created a table showing returns on interest rates, let's build on this structure to solve for a given r, t, or PV given the value of two of these variables and FV. We can record each step in the process in a dictionary, just as we did in the previous example.

Great work! You've combined several fundamental concepts from computing and finance in a single lesson. 

### Homework

Create a Jupyter notebook that explains the rule of 70 (or 72 if you prefer). Compare the rule of 70 to analytical and computational solutions.

> 1.For all interest rates from 1% to 10%, at intervals of 1%, calculate the length of time required for an investment to double in value for each interest rate. *Recall that for an investment that has doubled in size*: 
>
>>$\frac{FV}{PV} = 2$
>>
>>$2 = (1+r)^t$
>>
>>$ln(2) = tln(1+r)$
>>
>>$t = \frac{ln(2)}{ln(1+r)}$
>
>Use the above solution to solve for $t$ for each $r$. Print the solution in a table by using "\n" and "\t" in the >print function when appropriate.
>
>\*Your script *must* use a for loop or for loops to find the solutions.

>2.In a dictionary, save the length of time required to double the value of an investment for each interest rate. The structure of your dictionary should be as follows: use "Time to double" as a key in the first layer of the dictionary. This should point to another dictionary that indicates the number of periods  required to double the value of an investment for each interest rate. The first layer of keys will also include "Rule of 70" (or "... of 72") and "Computational Solution", each of which point to another dictionary where the approximated solutions will be saved. 
>
> Use the following to start. Solve the problem computationally, then ave the completed dictionary as a dataframe (import pandas; and pass the dictionary to a DataFrame). Save this dataframe as a csv.
>
>dct = {"Time to double": {r: np.log(2) / np.log(1+r/100) for r in range(1,11,1)}, "Rule of 70":{r:70 / r for r in range(1,11)}, "Computational Solution": {}}


### Graduate Homework
>3.Use for loops to create a list of prime numbers between 2 and 1000.

In [24]:
import numpy as np
dct = {"Time to double": {r: np.log(2) / np.log(1+r/100) for r in range(1,11,1)}, "Rule of 70":{r:70 / r for r in range(1,11)}, "Computational Solution": {}}
dct

{'Time to double': {1: 69.66071689357483,
  2: 35.0027887811465,
  3: 23.449772250437736,
  4: 17.672987685129698,
  5: 14.206699082890463,
  6: 11.895661045941875,
  7: 10.244768351058712,
  8: 9.006468342000588,
  9: 8.043231726932046,
  10: 7.272540897341713},
 'Rule of 70': {1: 70.0,
  2: 35.0,
  3: 23.333333333333332,
  4: 17.5,
  5: 14.0,
  6: 11.666666666666666,
  7: 10.0,
  8: 8.75,
  9: 7.777777777777778,
  10: 7.0},
 'Computational Solution': {}}